name: Mirror Repository

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Mirror Repository
        run: |
          git clone --bare https://github.com/umr-marbec/test_miroir
          cd OLD-REPOSITORY
          git push --mirror https://forge.ird.fr/marbec/test_miroir_github
