name: Mirror Repository

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup forge.ird.fr credentials
        run: git config --global url.https://${{ secrets.GITLAB_PAT }}@forge.ird.fr/.insteadOf https://forge.ird.fr/
      - name: Clone Repository
        run: |
          git clone --bare https://github.com/umr-marbec/test_miroir old-repo
      - name: Push to GitLab
        run: |
          cd old-repo
          git push --mirror https://forge.ird.fr/marbec/test_miroir_github
