name: GitHub to GitLab Mirror

on:
  push:
    branches:
      - main  # Vous pouvez adapter cette ligne selon la branche que vous souhaitez surveiller.
  pull_request:
    branches:
      - main  # Optionnel : si vous voulez que cela se déclenche aussi lors d'un PR vers la branche main.

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Check out GitHub repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Add Forge remote
        run: |
          git remote add forge https://oauth2:${{ secrets.FORGE_TOKEN }}@forge.ird.fr/umr-marbec/test_miroir.git
  
      - name: Push to Forge
        run: |
          git push --mirror forge
