name: GitHub to Git Mirror

on:
  push:   # Déclenche sur n'importe quel push sur n'importe quelle branche
    branches:
      - '**'  # Toutes les branches
    tags:
      - '**'  # Déclenche pour tous les pushs de tags
  pull_request:   # Déclenche aussi sur toute Pull Request
    branches:
      - '**'  # Toutes les branches
  delete:
    branches:
      - '**'  # Déclenche sur la suppression de n'importe quelle branche
    tags:
      - '**'  # Déclenche lors de la suppression de tous les tags

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository as bare
        run: |
          git clone --bare https://github.com/umr-marbec/test_miroir.git mon-depot-github.git

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@users.noreply.github.com"

      - name: Add forge remote
        run: |
          cd mon-depot-github.git
          git remote add mirror https://oauth2:${{ secrets.FORGE_TOKEN }}@forge.ird.fr/marbec/test_miroir_github.git
  
      - name: Push to forge
        run: |
          cd mon-depot-github.git
          git push --mirror mirror
