name: GitHub to Git Mirror with Release Assets

on:
  push:   # Déclenche sur n'importe quel push sur n'importe quelle branche
    branches:
      - '**'  # Toutes les branches
    tags:
      - '**'  # Déclenche pour tous les pushs de tags
  pull_request:   # Déclenche aussi sur toute Pull Request
    branches:
      - '**'  # Toutes les branches
  delete:
    branches:
      - '**'  # Déclenche sur la suppression de n'importe quelle branche
    tags:
      - '**'  # Déclenche lors de la suppression de tous les tags
  release:
    types:
      - created  # Déclenche lors de la création d'une release
      - published  # Déclenche lors de la publication d'une release
      - updated  # Déclenche lors de la mise à jour d'une release
      - deleted  # Déclenche lors de la suppression d'une release

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository as bare
        run: |
          git clone --bare https://github.com/umr-marbec/test_miroir.git mon-depot-github.git

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@users.noreply.github.com"

      - name: Add forge remote
        run: |
          cd mon-depot-github.git
          git remote add mirror https://oauth2:${{ secrets.FORGE_TOKEN }}@forge.ird.fr/marbec/test_miroir_github.git
  
      - name: Push to forge
        run: |
          cd mon-depot-github.git
          git push --mirror mirror

  download-release-assets:
    runs-on: ubuntu-latest
    needs: mirror # Attendre que le job "mirror" se termine

    steps:
      - name: Set up Git (Authentication)
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@users.noreply.github.com"
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}  # Utilisation du token GitHub

      - name: Fetch latest release from GitHub
        id: fetch_release
        run: |
          # Récupérer les informations de la dernière release
          RESPONSE=$(curl -s -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
            "https://api.github.com/repos/umr-marbec/test_miroir/releases/latest")
          
          # Extraire l'ID de la release
          RELEASE_ID=$(echo "$RESPONSE" | jq -r '.id')

          # Vérifier si RELEASE_ID a bien été extrait
          echo "Release ID: $RELEASE_ID"
          
          # Si RELEASE_ID est vide, échouer explicitement pour déboguer
          if [ -z "$RELEASE_ID" ]; then
            echo "Release ID is empty. Exiting."
            exit 1
          fi

          echo "RELEASE_ID=$RELEASE_ID" >> $GITHUB_ENV  # Passer l'ID de release comme variable d'environnement

      - name: Download release assets from GitHub
        run: |
          # Télécharger les assets de la release
          ASSETS=$(curl -s \
            -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
            "https://api.github.com/repos/umr-marbec/test_miroir/releases/${RELEASE_ID}/assets" \
            | jq -r '.[].browser_download_url')

          # Vérifier si des assets sont trouvés
          if [ -z "$ASSETS" ]; then
            echo "No assets found for this release."
            exit 0
          fi

          # Créer un répertoire pour les assets
          mkdir release-assets
          cd release-assets

          # Télécharger les fichiers des assets
          for URL in $ASSETS; do
            echo "Downloading $URL"
            curl -L -o "$(basename $URL)" -H "Authorization: token $GITHUB_TOKEN" "$URL"
          done

      - name: Push assets to Git repository
        run: |
          # Initialiser un dépôt Git et ajouter le dépôt distant cible
          cd release-assets
          git init
          git remote add origin https://<git-username>:${{ secrets.GIT_PASSWORD }}@<git-server-url>/<repo-name>.git
          git checkout -b release-assets

          # Ajouter les assets et pousser dans le dépôt Git
          git add .
          git commit -m "Add release assets"
          git push -u origin release-assets --force
